### ISSUE TITLE
How is the selfplay version going?

### ISSUE THREAD

**Issue by vigor95** [yhyu13/AlphaGOZero-python-tensorflow#11]
Is the training effective?

**Comment by yhyu13** [comment]
Hi,

I have gave my hope to leela zero😊. It takes 4 seconds to calculate each move (1600 search), meaning there is still hope in this project. I am updating it into AlphaZero so hopefully it can train well when the my next semester begin(January).

_Sent from my Samsung SAMSUNG-SM-G935A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
