### ISSUE TITLE
uvloop modle can not for windows

### ISSUE THREAD

**Issue by ZooDoz** [yhyu13/AlphaGOZero-python-tensorflow#5]
Collecting uvloop (from -r .\requirements.txt (line 6))
  Using cached uvloop-0.8.1.tar.gz
   RuntimeError: uvloop does not support Windows at the moment

can change this uvloop?

**Comment by yhyu13** [comment]
@ZooDoz 

You're fine. Just delete these two lines at the beginning of APV_MCTS*.py*:

```
import uvloop
asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

So that asyncio would use its default loop policy. Let me know if you have further trouble.

**Comment by yhyu13** [comment]
@ZooDoz 

This project still has long iterations ahead. So keep up with commits. Thanks!

**Comment by ZooDoz** [comment]
thanks for you job.
i am a new python player.  let me try.

**Comment by yhyu13** [comment]
@ZooDoz 

Be patient, let me know if you are having trouble.
